config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :companies do
    resources :claims, only: %i[create]
  end
  root 'companies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/claim.rb
class Claim < ApplicationRecord
  belongs_to :user
  belongs_to :company
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :claims, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :claims, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  def create
    @claim = Claim.new(claim_params)
    @claim.user = current_user
    @claim.company_id = params[:company_id]
    if @claim.save
      respond_to :js
    else
      redirect_to root_path, alert: 'El Reclamo no pudo ser Ingresado'
    end
  end

  private

  def claim_params
    params.require(:claim).permit(:claim)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!, only: %i[show create edit destroy]
  def index
    @companies = Company.all
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      respond_to :js
    else
      redirect_to root_path, alert: 'La compañia no ha sido creada'
    end
  end

  def show
    @company = Company.find(params[:id])
    @claim = Claim.new
    @claims = Claim.where(company_id: @company.id).reverse_order
  end

  def edit
    @company = Company.find(params[:id])
    respond_to :js
  end
  
  def update
    @company = Company.find(params[:id])
    @company.update(company_params)
    if @company.save
      respond_to :js
    else 
      redirect_to root_path, alert: 'Registro No actualizado Intente nuevamente'
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    respond_to :js
  end

  private

  def company_params
    params.require(:company).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/claims/create.js.erb
$('#claims').prepend("<div class='alert alert-warning' role='alert'><%=  @claim.claim%><span class='badge badge-success'><strong>By:</strong><%=@claim.user.email.split('@')[0]%></span></div>");
$('#claim_claim').val('');

app/views/companies/_claims_form.html.erb
<div class="row">
        <div class="col col-md-4">
                <%= form_with(model: [company, claim]) do |f| %>
                       <strong><%= f.label :Claim %></strong><br>
                        <%= f.text_area :claim %><br>
                        <%= f.submit 'Add Claim', class: 'btn btn-success'%>
                <% end %>
        </div>
</div>

app/views/companies/_company.html.erb
<tr id="<%= company.id%>">
        <th scope="row"><%= company.name %></th>
        <td><%= link_to "Show", company_path(company), class: 'btn btn-primary' %></td>
        <td><%= link_to "Editar",edit_company_path(company) , data:{ remote: true }, class: 'btn btn-warning' %></td>
        <td><%= link_to "Delete", company_path(company), method: :delete, data:{ confirm: "are you sure", remote: true}, class: 'btn btn-danger' %></td>
      </tr>

app/views/companies/_form.html.erb
<div class="row">
                <div class="col col-md-6">
                        <%= form_with(model: company) do |f|  %>
                                <%= f.label :Name_Company %>
                                <%= f.text_field :name, class: 'form-control'%>
                                <%= f.submit 'New Company', class: 'btn btn-success'%>
                        <% end %>
                </div>
        </div>

app/views/companies/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      ...
                    </div>
                    <div class="modal-footer">
                      
                    </div>
                  </div>
                </div>
              </div>

app/views/companies/create.js.erb
$('#companies').append("<%= j render 'companies/company', company: @company %>")
$('#company_name').val('');

app/views/companies/destroy.js.erb
$('#<%= @company.id%>').fadeOut();

app/views/companies/edit.js.erb
$('.modal-body').html("<%= j render 'form', company: @company%>");
$('#exampleModal').modal('show');

app/views/companies/index.html.erb
<h1>companies</h1>
<%= render  "form", company: @company %>
<div class="row">
        <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">Company Name</th>
                    <th scope="col">#</th>
                    <th scope="col">#</th>
                    <th scope="col">#</th>
                  </tr>
                </thead>
                <tbody id="companies">
                  <%= render @companies %>
                </tbody>
              </table>
              <%= render  "modal" %>

</div>

      
      

app/views/companies/show.html.erb
<h1>Claims for <strong><%= @company.name%></strong></h1> 

 <%= render  "claims_form", company: @company, claim: @claim %>

 <div class="row">
         <div class="col col-md-6">
                 <div id="claims">
                        <% @claims.each do |claim| %>
                        <div class="alert alert-warning" role="alert">
                                        <%=  claim.claim%>
                                        <span class="badge badge-success"><strong>By:</strong><%=claim.user.email.split('@')[0]%></span>
                                        </div>
                                      
                        
                        <% end %>
                 </div>

         </div>
 </div>

app/views/companies/update.js.erb
$('#<%= @company.id%>').replaceWith("<%= j render 'companies/company', company: @company %>")
$('#exampleModal').modal('hide');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PruebaRailsAjax</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>
      
  </head>

  <body>
    <%= render  "shared/navbar" %>
    <div class="container">
        <%= yield %>
    </div>
 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="#">MVP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav">
                    <li class="nav-item active">
                      <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <% if user_signed_in? %>
                    <li class="nav-item">
                        <a class="nav-link" data-method="DELETE" href="<%= destroy_user_session_path%>">Sign Out</a>
                      </li>
                    <% else %>
                    <li class="nav-item">
                        <a class="nav-link" href="<%= new_user_session_path%>">Sign In</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="<%= new_user_registration_path%>" tabindex="-1" aria-disabled="true">Sing Up</a>
                      </li>
                    <% end %>
                    </ul>
                </div>
              </nav>